#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for i in $(ls "$DIR"); do
  if [ "$i" != "install" ] && [ "$i" != "UpdateVimPlugins" ] && [ "$i" != "README.md" ]; then
    if [ -e "$HOME/.$i" ]; then
      read -p "$HOME/.$i exists! Delete? [y/N] " -n 1 -r
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        #probably would be better to explicitly check
        #if directory before -r and -n
        rm -rf "$HOME/.$i"
        ln -sn "$DIR/$i" "$HOME/.$i"
      fi
      echo ""
    else
      ln -sn "$DIR/$i" "$HOME/.$i"
    fi
  fi
done

git submodule update --init --recursive
git submodule foreach git pull origin master
ln -fsn "$DIR"/vim/pathogen/autoload "$DIR"/vim/
mkdir -p "$HOME"/.local/share/vim/{backup,swap,undo}

#Very specific to Arch
yaourt -S boost python-powerline-git

echo "Compiling YouCompleteMe"
cd "$DIR"/vim/bundle/YouCompleteMe
./install.sh

read -p "Auto install exuberant-ctags? [y/N] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo ""
  git clone git://github.com/jakedouglas/exuberant-ctags.git "$HOME"/exuberant-ctags
  cd "$HOME"/exuberant-ctags
  ./configure
  make
  sudo make install
  rm -rf "$HOME"/exuberant-ctags
fi
echo ""
