#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

git submodule foreach git pull origin master

echo "Compiling YouCompleteMe"
cd "$DIR"/vim/bundle/YouCompleteMe
./install.sh

read -p "Auto install exuberant-ctags? [y/N] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    git clone git://github.com/jakedouglas/exuberant-ctags.git ~/exuberant-ctags
    cd ~/exuberant-ctags
    ./configure
    make
    sudo make install
    rm -rf ~/exuberant-ctags
fi
echo ""
